## Importar librería "pandas"

In [1]:
import pandas as pd

## Leer el archivo ventas_compras.xlsx

In [2]:
df = pd.read_excel('ventas_compras.xlsx', sheet_name = [0,1])

## Visualizar los datos de Ventas y Compras

In [3]:
df_ventas = df[0] 
df_ventas.head()

       Cliente     Producto  Cantidad  Precio Unitario       Fecha
0  Cliente_100  Producto_10        11           316.29  2023-11-23
1  Cliente_102   Producto_3        65           449.64  2023-11-23
2  Cliente_104  Producto_47        36           359.11  2023-11-23
3  Cliente_114  Producto_78        84           106.08  2023-11-23
4  Cliente_115  Producto_32         9           429.76  2023-11-23

In [4]:
df_compras = df[1]
df_compras.head()

       Proveedor      Producto  Cantidad  Precio Unitario       Fecha
0  Proveedor_229  Producto_146        13           114.59  2024-11-22
1  Proveedor_253  Producto_172        28           831.88  2024-11-22
2  Proveedor_047  Producto_190        69           521.67  2024-11-22
3  Proveedor_300    Producto_7        82           431.63  2024-11-22
4  Proveedor_288  Producto_183       158           619.19  2024-11-22

## Total de ventas por cliente

In [5]:
df_ventas['total_ventas_cliente'] = df_ventas['Producto']

df_total_ventas = df_ventas[['Cliente', 'total_ventas_cliente']].groupby(by=['Cliente']).count()
df_total_ventas

             total_ventas_cliente
Cliente
Cliente_001                    58
Cliente_002                    48
Cliente_003                    43
Cliente_004                    39
Cliente_005                    56
...                           ...
Cliente_196                    46
Cliente_197                    52
Cliente_198                    60
Cliente_199                    47
Cliente_200                    48

[200 rows x 1 columns]

## Total de compras por proveedor

In [6]:
df_compras['total_compras_proveedor'] = df_compras['Producto']

df_total_compras = df_compras[['Proveedor', 'total_compras_proveedor']].groupby(by=['Proveedor']).count()
df_total_compras

               total_compras_proveedor
Proveedor
Proveedor_001                       27
Proveedor_002                       25
Proveedor_003                       33
Proveedor_004                       37
Proveedor_005                       45
...                                ...
Proveedor_296                       40
Proveedor_297                       30
Proveedor_298                       26
Proveedor_299                       31
Proveedor_300                       34

[300 rows x 1 columns]

## Exportar a Excel las 2 hojas

In [7]:
with pd.ExcelWriter('total_ventas_compras.xlsx') as writer:
    df_total_ventas.to_excel(writer,\
                            sheet_name="Total de Ventas por Cliente")
    df_total_compras.to_excel(writer,\
                            sheet_name="Total de Compras por Proveedor")